name: Call API for Line 9103

on:
  schedule:
    - cron: '18 4 * * 1-5' # 4:15 UTC = 5:15 CET (pondělí až pátek)
  workflow_dispatch:
jobs:
  call-api-9103:
    runs-on: ubuntu-latest

    steps:
      - name: Call API for line 9103
        run: |
          curl -X GET "https://alive-truckit-cz.vercel.app/api/check-deadlines/9103" \
          -H "x-api-key: ${{ secrets.API_KEY }}"
