name: Scheduled API Calls

on:
  schedule:
    # Cron syntax (UTC time):
    # 8:55 CET = 7:55 UTC
    - cron: '8 8 * * 6'
    # 9:00 CET = 8:00 UTC
    - cron: '9 8 * * 6'
    # 9:05 CET = 8:05 UTC
    - cron: '10 8 * * 6'

jobs:
  clear-db:
    if: github.event.schedule == '8 8 * * 6'
    runs-on: ubuntu-latest

    steps:
      - name: Clear Database
        run: |
          curl -X DELETE "https://alive-truckit-cz.vercel.app/api/clear-db" \
          -H "x-api-key: ${{ secrets.API_KEY }}"

  call-api-9100:
    if: github.event.schedule == '9 8 * * 6'
    runs-on: ubuntu-latest

    steps:
      - name: Call API for line 9100
        run: |
          curl -X GET "https://alive-truckit-cz.vercel.app/api/check-deadlines/9100" \
          -H "x-api-key: ${{ secrets.API_KEY }}"

  call-api-9103:
    if: github.event.schedule == '10 8 * * 6'
    runs-on: ubuntu-latest

    steps:
      - name: Call API for line 9103
        run: |
          curl -X GET "https://alive-truckit-cz.vercel.app/api/check-deadlines/9103" \
          -H "x-api-key: ${{ secrets.API_KEY }}"
