name: Clear Database

on:
  schedule:
    - cron: '17 8 * * 6' # 55 7 * * 1-5 = 7:55 UTC = 8:55 CET (pondělí až pátek)

jobs:
  clear-db:
    runs-on: ubuntu-latest

    steps:
      - name: Clear Database
        run: |
          curl -X DELETE "https://alive-truckit-cz.vercel.app/api/clear-db" \
          -H "x-api-key: ${{ secrets.API_KEY }}"
